# Generated by Django 2.0.6 on 2018-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180607_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='header',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='zdrQxHVE6asrL3jL4P2n', max_length=20),
        ),
    ]
